using Godot;
using System;
using System.Collections.Generic;

public partial class LevelController : Node
{
    private static List<LevelData> Levels { get; } = new List<LevelData>()
    {
        new LevelData(
            "Level XX - Chaos",
            "One copy of everything - go wild!",
            new Deck(false,
                (1, new CardBody("Ringabod")),
                (1, new CardBody("Snail")),
                (1, new CardBody("Angry Snail")),
                (1, new CardBody("Bee")),
                (1, new CardBody("Biped Blob")),
                (1, new CardBody("Butterfly")),
                (1, new CardBody("Flutter Fly")),
                (1, new CardBody("Scorpion")),
                (1, new CardBody("Dry Scorpion")),
                (1, new CardBody("4-Leg Mammal")),
                (1, new CardBody("Land Shark")),
                (1, new CardBody("Sky Shark")),
                (1, new CardBody("Merworm")),
                (1, new CardBody("Turtle")),
                (1, new CardBody("Ninja Turtle")),
                (1, new CardBodyPart("Beholder")),
                (1, new CardBodyPart("Brain")),
                (1, new CardBodyPart("Alien")),
                (1, new CardBodyPart("Bulldog")),
                (1, new CardBodyPart("Fly")),
                (1, new CardBodyPart("Cat")),
                (1, new CardBodyPart("Gnome")),
                (1, new CardBodyPart("Mosquito")),
                (1, new CardBodyPart("Woodpecker")),
                (1, new CardBodyPart("Beholder")),
                (1, new CardBodyPart("Tentacle")),
                (1, new CardBodyPart("Bear Arm")),
                (1, new CardBodyPart("Cursor")),
                (1, new CardBodyPart("Skelly Arm")),
                (1, new CardBodyPart("Spiky Arm")),
                (1, new CardBodyPart("Lsr Swd 3000")),
                (1, new CardBodyPart("T-Rex")),
                (1, new CardBodyPart("Chicken Leg")),
                (1, new CardBodyPart("Cockatrice")),
                (1, new CardBodyPart("Wheel")),
                (1, new CardBodyPart("Frog")),
                (1, new CardBodyPart("House Cat")),
                (1, new CardBodyPart("Peg Leg")),
                (1, new CardBodyPart("Skelly Leg")),
                (1, new CardBodyPart("Spiky Leg"))),
            new Deck(true,
                (1, new CardBody("Ringabod")),
                (1, new CardBody("Snail")),
                (1, new CardBody("Angry Snail")),
                (1, new CardBody("Bee")),
                (1, new CardBody("Biped Blob")),
                (1, new CardBody("Butterfly")),
                (1, new CardBody("Flutter Fly")),
                (1, new CardBody("Scorpion")),
                (1, new CardBody("Dry Scorpion")),
                (1, new CardBody("4-Leg Mammal")),
                (1, new CardBody("Land Shark")),
                (1, new CardBody("Sky Shark")),
                (1, new CardBody("Merworm")),
                (1, new CardBody("Turtle")),
                (1, new CardBody("Ninja Turtle")),
                (1, new CardBodyPart("Beholder")),
                (1, new CardBodyPart("Brain")),
                (1, new CardBodyPart("Alien")),
                (1, new CardBodyPart("Bulldog")),
                (1, new CardBodyPart("Fly")),
                (1, new CardBodyPart("Cat")),
                (1, new CardBodyPart("Gnome")),
                (1, new CardBodyPart("Mosquito")),
                (1, new CardBodyPart("Woodpecker")),
                (1, new CardBodyPart("Beholder")),
                (1, new CardBodyPart("Tentacle")),
                (1, new CardBodyPart("Bear Arm")),
                (1, new CardBodyPart("Cursor")),
                (1, new CardBodyPart("Skelly Arm")),
                (1, new CardBodyPart("Spiky Arm")),
                (1, new CardBodyPart("Lsr Swd 3000")),
                (1, new CardBodyPart("T-Rex")),
                (1, new CardBodyPart("Chicken Leg")),
                (1, new CardBodyPart("Cockatrice")),
                (1, new CardBodyPart("Wheel")),
                (1, new CardBodyPart("Frog")),
                (1, new CardBodyPart("House Cat")),
                (1, new CardBodyPart("Peg Leg")),
                (1, new CardBodyPart("Skelly Leg")),
                (1, new CardBodyPart("Spiky Leg"))))
    };
}
